<?php echo $this->headTitle('Labels') ?>

<h1>Labels</h1>
<button type="button" class="btn btn-primary btn-block" id="add_label">Add label</button>
<div class="data_table">
    <table id="labels_table" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th style="width: 15%">Label name</th>
                <th>Default text</th>
                <th>Edit</th>
                <th>Delete</th>
                <th>Translations</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div id="form"></div>